### PR TITLE
Sonarxml

### PR DESCRIPTION
**Pull request by maddingo**
I implemented a very first draft of the sonarxml output format that created coverage reports for Sonar's Generic Coverage Plugin. The whole report generation could probably refactored. The implementation tried to add as few changes as possible. The output name is also hard-coded. for the time being.

### CODE REVIEW

**Comment by rliesenfeld** [comment]
Thanks!

I would like to make some changes before merging any commits, though:

1. The ".gitignore" file doesn't really need to be commited (I use IntelliJ), so I would prefer to keep it out.
2. The changes to the three pom.xml files are not necessary either, and the project doesn't use snapshots. So, let's keep these out as well.
3. The new "sonarxml" output format would be a "data file", not a "report". The "reporting" package is for end user reports only, more specifically the HTML report. So, new code for XML output should go into a new "XmlFile" class (or "SonarXmlFile"), in the same package as the existing "AccretionFile" class which produces the "coverage.ser" data file.
4. I can make these adjustments later, but if possible, new/modified code should stick to the project's code style rules: 3 spaces of indentation without TAB characters, star imports, blank lines before/after conditional/looping/try statements.
5. The changes made to CoverageReport.java, ClassWithNestedClassesTest.java, and CustomClassLoadingTest.java would need to be undone. (Those tests are passing for me, both from IntelliJ and from Maven, so I don't know why they fail for you - may need to have a look later.)
6. The "XmlCoverageReportTest" test class should be moved to the parent package and renamed to "XmlFileTest" (or "SonarXmlFileTest"). The test should exercise a couple of sample classes, instantiate "XmlFile" and call it to generate the xml file from current coverage data, then read this file and compare  it with the expected (hardcoded) contents; there should be no "coverage.ser" file involved.

What do you think?

**Comment by maddingo** [comment]
First of all, you are free to take the code and modify it before merging it into master. Do you want me to do the changes? From your posting it sounded more like you wanted to do it.
Here are some remarks on your posting above:
1. The .gitignore would make it easier for developers using Eclipse to contribute to the project. Therefor I think the .gitignore should be added to the project
2. The project structure doesn't follow Maven conventions, e.g. file structure. This requires a lot of unnecessary configuration in the POM. jmockit uses the Sonatype staging plugin which supports maven's  release plugin, which makes releasing a new version very easy. The project would probably also benefit from being one Maven project with 3 modules.
3. I didn't see it this way. 
4. Sorry for screwing up the format. I tried to stick with your code style.
5. CoverageReport.getOrChooseOutputDirectory is used in XmlCoverageReport and is therefor public. The other changes are results of an attempt to create a class hierarchy. The attempt failed and the code can be reverted. Sorry for that.
6. I agree, the test should be improved.

**Comment by rliesenfeld** [comment]
Duplicate of #61

**Comment by maddingo** [comment]
I am a bit unsure now whether jmockit will support sonarxml or not, both #61 and #228 are closed without the code being merged.

**Pull request closed without merging**
